// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdFn4i4gzFLAm51qD07VSKmeqRh4MLBsM',
    appId: '1:1051609421686:web:3ead108bcaca2db95c8c57',
    messagingSenderId: '1051609421686',
    projectId: 'free-wheel-bc98d',
    authDomain: 'free-wheel-bc98d.firebaseapp.com',
    storageBucket: 'free-wheel-bc98d.firebasestorage.app',
    measurementId: 'G-LFEY647PH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIj3elocPIXAri0ThrrqY5c39a18sx3vU',
    appId: '1:1051609421686:android:43086da75b4a2adb5c8c57',
    messagingSenderId: '1051609421686',
    projectId: 'free-wheel-bc98d',
    storageBucket: 'free-wheel-bc98d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmdoZRcDDcU8WsFv8hIHXKpaDngsuRAuc',
    appId: '1:1051609421686:ios:be0a990758b1bd7f5c8c57',
    messagingSenderId: '1051609421686',
    projectId: 'free-wheel-bc98d',
    storageBucket: 'free-wheel-bc98d.firebasestorage.app',
    iosBundleId: 'com.example.freewheelMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmdoZRcDDcU8WsFv8hIHXKpaDngsuRAuc',
    appId: '1:1051609421686:ios:be0a990758b1bd7f5c8c57',
    messagingSenderId: '1051609421686',
    projectId: 'free-wheel-bc98d',
    storageBucket: 'free-wheel-bc98d.firebasestorage.app',
    iosBundleId: 'com.example.freewheelMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdFn4i4gzFLAm51qD07VSKmeqRh4MLBsM',
    appId: '1:1051609421686:web:74db3db8e8b990b25c8c57',
    messagingSenderId: '1051609421686',
    projectId: 'free-wheel-bc98d',
    authDomain: 'free-wheel-bc98d.firebaseapp.com',
    storageBucket: 'free-wheel-bc98d.firebasestorage.app',
    measurementId: 'G-WYYV9YBH34',
  );
}
